import React from 'react';
import DeleteIcon from "@material-ui/icons/Delete";
import IconButton from "@material-ui/core/IconButton";
import {CardProps} from "@material-ui/core/Card/Card";
import {TradeOperationModel} from "../../../models/TradeOperationModel";
import {money} from "../../../utils/money";
import ListItem from "@material-ui/core/ListItem";
import ListItemIcon from "@material-ui/core/ListItemIcon";
import AutorenewIcon from '@material-ui/icons/Autorenew';
import TrendingDown from "@material-ui/icons/TrendingDown";
import ListItemText from "@material-ui/core/ListItemText";
import ListItemSecondaryAction from "@material-ui/core/ListItemSecondaryAction";
import {makeStyles} from "@material-ui/styles";
import {Theme} from "@material-ui/core/styles";
import {easyDate} from "../../../utils/date-util";
import ChevronRightIcon from '@material-ui/icons/ChevronRight';
import {notStonksTextColor, stonksTextColor} from "../../../theme/colors";

type Props = CardProps & {
    tradeOperation: TradeOperationModel
    onEditClick: (item: TradeOperationModel) => void
    onDeleteClick: (item: TradeOperationModel) => void
}

const useStyles = makeStyles((theme: Theme) => ({
    unknownAccount: {
        color: theme.palette.error.main,
    },
    secondaryText: {
        display: 'flex',
        alignItems: 'center',
    },
}));

const Amount = ({operation}: { operation: TradeOperationModel }) => {
    const color = operation.amount < 0 ? notStonksTextColor : stonksTextColor;
    return <span style={{color}}>{money(operation.amount)}</span>
};

export const TradeOperationCard = (props: Props) => {
    const {tradeOperation, onEditClick, onDeleteClick} = props;
    const classes = useStyles();

    return (
        <ListItem button onClick={() => onEditClick(tradeOperation)}>
            <ListItemIcon>
                {tradeOperation.amount < 0 ? <TrendingDown/> : <AutorenewIcon/>}
            </ListItemIcon>
            <ListItemText
                primary={<><Amount operation={tradeOperation}/></>}
                secondary={(
                    <span className={classes.secondaryText}>
            {/*Issued*/}
                        {(tradeOperation as any)?.issuerCashAccount?.name ||
                        <span className={classes.unknownAccount}>Unknown account</span>}
                        {' '}
                        {easyDate(tradeOperation.dateIssued)}

                        <ChevronRightIcon/>

                        {/*Acquired*/}
                        {(tradeOperation as any)?.acquirerCashAccount?.name ||
                        <span className={classes.unknownAccount}>Unknown account</span>}
                        {' '}
                        {easyDate(tradeOperation.dateAcquired)}
          </span>
                )}
            />
            {/*TODO: Don't use 'any'. Remove the MODELS and use the autogenerated ts code.*/}
            <ListItemSecondaryAction>
                <IconButton edge="end" aria-label="delete" onClick={() => onDeleteClick(tradeOperation)}>
                    <DeleteIcon/>
                </IconButton>
            </ListItemSecondaryAction>
        </ListItem>
    );
};
