import React from 'react';
import DeleteIcon from "@material-ui/icons/Delete";
import IconButton from "@material-ui/core/IconButton";
import {CardProps} from "@material-ui/core/Card/Card";
import {TradeOperationModel} from "../../../models/TradeOperationModel";
import ListItem from "@material-ui/core/ListItem";
import ListItemText from "@material-ui/core/ListItemText";
import ListItemSecondaryAction from "@material-ui/core/ListItemSecondaryAction";
import {makeStyles} from "@material-ui/styles";
import {Theme} from "@material-ui/core/styles";
import {easyDate} from "../../../utils/date-util";
import ChevronRightIcon from '@material-ui/icons/ChevronRight';
import {notStonksTextColor, stonksTextColor} from "../../../theme/colors";

type Props = CardProps & {
    tradeOperation: TradeOperationModel
    onEditClick: (item: TradeOperationModel) => void
    onDeleteClick: (item: TradeOperationModel) => void
}

const useStyles = makeStyles((theme: Theme) => ({
    unknownAccount: {
        color: theme.palette.error.main,
    },
    primaryText: {
        display: 'flex',
        alignItems: 'center',
    },
    secondaryText: {
        display: 'flex',
        alignItems: 'center',
    },
}));

export const TradeOperationCard = (props: Props) => {
    const {tradeOperation, onEditClick, onDeleteClick} = props;
    const classes = useStyles();

    return (
        <ListItem button onClick={() => onEditClick(tradeOperation)}>
            <ListItemText
                primary={<span className={classes.primaryText}>
                    <span
                        style={{color: notStonksTextColor}}>{tradeOperation.price}{tradeOperation.issuerCurrency}</span>
                    <ChevronRightIcon/>
                    <span
                        style={{color: stonksTextColor}}>{tradeOperation.amount}{tradeOperation.acquirerCurrency}</span>
                </span>}
                secondary={(
                    <span className={classes.secondaryText}>
                        <span style={{color: notStonksTextColor}}>
                        {(tradeOperation as any)?.issuerCashAccount?.name ||
                        <span className={classes.unknownAccount}>Unknown account</span>}
                            {' '}
                            {easyDate(tradeOperation.dateIssued)}
                        </span>

                        <ChevronRightIcon/>

                        <span style={{color: stonksTextColor}}>
                        {(tradeOperation as any)?.acquirerCashAccount?.name ||
                        <span className={classes.unknownAccount}>Unknown account</span>}
                            {' '}
                            {easyDate(tradeOperation.dateAcquired)}
                        </span>
          </span>
                )}
            />
            {/*TODO: Don't use 'any'. Remove the MODELS and use the autogenerated ts code.*/}
            <ListItemSecondaryAction>
                <IconButton edge="end" aria-label="delete" onClick={() => onDeleteClick(tradeOperation)}>
                    <DeleteIcon/>
                </IconButton>
            </ListItemSecondaryAction>
        </ListItem>
    );
};
