import React from 'react';
import DeleteIcon from "@material-ui/icons/Delete";
import IconButton from "@material-ui/core/IconButton";
import {CardProps} from "@material-ui/core/Card/Card";
import {FlowOperationModel} from "../../../models/FlowOperationModel";
import {money} from "../../../utils/money";
import ListItem from "@material-ui/core/ListItem";
import ListItemIcon from "@material-ui/core/ListItemIcon";
import TrendingUpIcon from "@material-ui/icons/TrendingUp";
import TrendingDown from "@material-ui/icons/TrendingDown";
import ListItemText from "@material-ui/core/ListItemText";
import ListItemSecondaryAction from "@material-ui/core/ListItemSecondaryAction";
import {makeStyles} from "@material-ui/styles";
import {Theme} from "@material-ui/core/styles";
import {easyDate} from "../../../utils/date-util";

type Props = CardProps & {
  flowOperation: FlowOperationModel
  onEditClick: (item: FlowOperationModel) => void
  onDeleteClick: (item: FlowOperationModel) => void
}

const useStyles = makeStyles((theme: Theme) => ({
  unknownAccount: {
    color: theme.palette.error.main,
  },
}));

export const FlowOperationCard = (props: Props) => {
  const {flowOperation, onEditClick, onDeleteClick} = props;
  const classes = useStyles();

  return (
    <ListItem button onClick={() => onEditClick(flowOperation)}>
      <ListItemIcon>
        {flowOperation.amount < 0 ? <TrendingDown/> : <TrendingUpIcon/>}
      </ListItemIcon>
      <ListItemText
        primary={flowOperation.description}
        secondary={(
          <>
            {money(flowOperation.amount)}
            {' - '}
            {(flowOperation as any)?.issuerCashAccount?.name ||
            <span className={classes.unknownAccount}>Unknown account</span>}
            {' - '}
            {easyDate(flowOperation.dateIssued)}
          </>
        )}
      />
      {/*TODO: Don't use 'any'. Remove the MODELS and use the autogenerated ts code.*/}
      <ListItemSecondaryAction>
        <IconButton edge="end" aria-label="delete" onClick={() => onDeleteClick(flowOperation)}>
          <DeleteIcon/>
        </IconButton>
      </ListItemSecondaryAction>
    </ListItem>
  );
};
