import React from 'react';
import DeleteIcon from "@material-ui/icons/Delete";
import IconButton from "@material-ui/core/IconButton";
import {CardProps} from "@material-ui/core/Card/Card";
import {FlowOperationModel} from "../../../models/FlowOperationModel";
import {money} from "../../../utils/money";
import ListItem from "@material-ui/core/ListItem";
import ListItemIcon from "@material-ui/core/ListItemIcon";
import TrendingUpIcon from "@material-ui/icons/TrendingUp";
import TrendingDown from "@material-ui/icons/TrendingDown";
import ListItemText from "@material-ui/core/ListItemText";
import ListItemSecondaryAction from "@material-ui/core/ListItemSecondaryAction";
import {makeStyles} from "@material-ui/styles";
import {Theme} from "@material-ui/core/styles";
import {easyDate} from "../../../utils/date-util";
import {notStonksTextColor, stonksTextColor} from "../../../theme/colors";

type Props = CardProps & {
    model: FlowOperationModel
    onEditClick: (item: FlowOperationModel) => void
    onDeleteClick: (item: FlowOperationModel) => void
}

const useStyles = makeStyles((theme: Theme) => ({
    unknownAccount: {
        color: theme.palette.error.main,
    },
}));

const Amount = ({operation}: { operation: FlowOperationModel }) => {
    const color = operation.amount < 0 ? notStonksTextColor : stonksTextColor;
    return <span style={{color}}>{money(operation.amount)}</span>
};

export const FlowOperationCard = (props: Props) => {
    const {model, onEditClick, onDeleteClick} = props;
    const classes = useStyles();

    return (
        <ListItem button onClick={() => onEditClick(model)}>
            <ListItemIcon>
                {model.amount < 0 ? <TrendingDown/> : <TrendingUpIcon/>}
            </ListItemIcon>
            <ListItemText
                primary={model.description}
                secondary={(
                    <>
                        <Amount operation={model}/>
                        {' - '}
                        {(model as any)?.issuerCashAccount?.name ||
                        <span className={classes.unknownAccount}>Unknown account</span>}
                        {' - '}
                        {easyDate(model.dateIssued)}
                    </>
                )}
            />
            {/*TODO: Don't use 'any'. Remove the MODELS and use the autogenerated ts code.*/}
            <ListItemSecondaryAction>
                <IconButton edge="end" aria-label="delete" onClick={() => onDeleteClick(model)}>
                    <DeleteIcon/>
                </IconButton>
            </ListItemSecondaryAction>
        </ListItem>
    );
};
